# Generated by Django 5.0.5 on 2024-05-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("glucose", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="glucoselevel",
            options={"ordering": ["-device_timestamp"]},
        ),
        migrations.RemoveField(
            model_name="glucoselevel",
            name="details",
        ),
        migrations.AddField(
            model_name="glucoselevel",
            name="depotinsulin",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="glucoselevel",
            name="glukose_scan_mg_dL",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="glucoselevel",
            name="glukose_teststreifen_mg_dL",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="glucoselevel",
            name="insulin_anderung_durch_anwender",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="glucoselevel",
            name="keton_mmol_L",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="glucoselevel",
            name="kohlenhydrate_gramm",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="glucoselevel",
            name="kohlenhydrate_portionen",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="glucoselevel",
            name="korrekturinsulin",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="glucoselevel",
            name="mahlzeiteninsulin",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="glucoselevel",
            name="nicht_numerische_nahrungsdaten",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="glucoselevel",
            name="nicht_numerisches_depotinsulin",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="glucoselevel",
            name="nicht_numerisches_schnellwirkendes_insulin",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="glucoselevel",
            name="notizen",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="glucoselevel",
            name="schnellwirkendes_insulin",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="glucoselevel",
            name="glucose_value_history",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="glucoselevel",
            name="recording_type",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
