# Generated by Django 5.0.5 on 2024-05-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("glucose", "0003_device_device_name_83218f_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
