# Generated by Django 5.0.5 on 2024-05-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("glucose", "0004_alter_user_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(
                default="password", max_length=128, verbose_name="password"
            ),
            preserve_default=False,
        ),
    ]
