name: Continuous Integration and Delivery

on: [ push ]

env:
  IMAGE: ghcr.io/${{ github.repository }}/una_test
  USER: una_user
  DB_NAME: una_test
  DB_USER: una_user
  DB_PASSWORD: una_password

jobs:
  build:
    name: Build Docker Image
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Log in to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push builder Image
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile.prod
          push: true
          tags: ${{ env.IMAGE }}-builder:latest
          build-args: |
            SECRET_KEY=$SECRET_KEY
          cache-from: type=registry,ref=${{ env.IMAGE }}-builder:latest
          cache-to: type=inline

      - name: Build and push final Image
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile.prod
          push: true
          tags: ${{ env.IMAGE }}-final:latest
          build-args: |
            SECRET_KEY=$SECRET_KEY
          cache-from: type=registry,ref=${{ env.IMAGE }}-final:latest
          cache-to: type=inline

  test:
    name: Test docker Image
    permissions: write-all
    runs-on: ubuntu-latest
    needs: build

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ env.DB_NAME }}
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Django Unit tests
        env:
          DJANGO_ALLOWED_HOSTS: localhost
          SECRET_KEY: cff7978cc78aafa256f4ec926508567981578f80e16c313303
          DB_HOST: localhost
          DB_NAME: ${{ env.DB_NAME }}
          DB_USERNAME: ${{ env.DB_USER }}
          DB_PASSWORD: ${{ env.DB_PASSWORD }}
          DB_PORT: 5432
        run: python manage.py test

      - name: Install dev requirements
        run: pip install -r requirements-dev.txt

      - name: Black
        run: python -m black . --check

      - name: isort
        run: python -m isort . --profile black --check-only

      - name: Ruff
        uses: chartboost/ruff-action@v1
        with:
          args: 'format --check'